# Generated by Django 3.2.18 on 2023-03-21 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import outscapebooking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80, verbose_name='Your first name*')),
                ('last_name', models.CharField(max_length=80, verbose_name='Your last name*')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Your email address*')),
                ('mobile', models.CharField(help_text='[Indicate your country code]', max_length=14, verbose_name='Your phone number*')),
                ('bookdate', models.DateField(help_text='[It is not possible to book the current day]', validators=[outscapebooking.models.Booking.validate_bookdate], verbose_name='The booking date*')),
                ('timeslot', models.CharField(choices=[('10:00-13:00', '10:00-13:00'), ('11:00-14:00', '11:00-14:00'), ('12:00-15:00', '12:00-15:00'), ('13:00-16:00', '13:00-16:00'), ('14:00-17:00', '14:00-17:00'), ('15:00-18:00', '15:00-18:00'), ('16:00-19:00', '16:00-19:00')], help_text='[The game lasts for the duration of the slot]', max_length=40, verbose_name='Choose your time slot*')),
                ('players', models.PositiveIntegerField(help_text="[You can't reserve for more than 10 players]", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of players*')),
                ('tickets', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Number of public transport tickets')),
                ('comment', models.TextField(blank=True, max_length=300, verbose_name='Your comment')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Declined')], default=0)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bookdate'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('bookdate', 'timeslot'), name='unique_booking'),
        ),
    ]
