# Generated by Django 3.2.18 on 2023-03-08 13:04

import django.core.validators
from django.db import migrations, models
import outscapebooking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=14)),
                ('bookdate', models.DateField(help_text='DD-MM-YYYY', validators=[outscapebooking.models.Booking.validate_bookdate])),
                ('timeslot', models.CharField(choices=[('10:00-13:00', '10:00-13:00'), ('11:00-14:00', '11:00-14:00'), ('12:00-15:00', '12:00-15:00'), ('13:00-16:00', '13:00-16:00'), ('14:00-17:00', '14:00-17:00'), ('15:00-18:00', '15:00-18:00'), ('16:00-19:00', '16:00-19:00')], max_length=40)),
                ('players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tickets', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='BVG tickets needed')),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Declined')], default=0)),
            ],
            options={
                'ordering': ['bookdate'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('bookdate', 'timeslot'), name='unique_booking'),
        ),
    ]
