# Generated by Django 3.2.18 on 2023-03-28 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=80, verbose_name='Your first name*'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.CharField(help_text='[Indicate your country code, without space. E.g:+336xxxxxxx/+490157xxxxxxxx]', max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Your phone number*'),
        ),
    ]
