# Generated by Django 3.2.18 on 2023-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0003_auto_20230328_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(error_messages={'required': 'Username already taken. (Panda)'}, max_length=254, verbose_name='Your email address*'),
        ),
    ]
