# Generated by Django 3.2.18 on 2023-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0003_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.PositiveIntegerField(),
        ),
    ]
