# Generated by Django 3.2.18 on 2023-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0004_auto_20230302_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
