# Generated by Django 3.2.18 on 2023-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0005_auto_20230302_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='BVG tickets needed'),
        ),
    ]
