# Generated by Django 3.2.18 on 2023-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0006_alter_booking_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '10:00-13:00'), (1, '11:00-14:00'), (2, '12:00-15:00'), (3, '13:00-16:00'), (4, '14:00-17:00'), (5, '15:00-18:00'), (6, '16:00-19:00')], default='05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='DD-MM-YYYY'),
        ),
    ]
