# Generated by Django 3.2.18 on 2023-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0007_auto_20230302_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.CharField(choices=[(10, '10:00-13:00'), (11, '11:00-14:00'), (12, '12:00-15:00'), (13, '13:00-16:00'), (14, '14:00-17:00'), (15, '15:00-18:00'), (16, '16:00-19:00')], max_length=11),
        ),
    ]
