# Generated by Django 3.2.18 on 2023-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0008_alter_booking_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hour',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.CharField(choices=[(0, '10:00-13:00'), (1, '11:00-14:00'), (2, '12:00-15:00'), (3, '13:00-16:00'), (4, '14:00-17:00'), (5, '15:00-18:00'), (6, '16:00-19:00')], max_length=11),
        ),
    ]
