# Generated by Django 3.2.18 on 2023-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outscapebooking', '0009_auto_20230302_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hour',
            field=models.TimeField(default='05:00'),
            preserve_default=False,
        ),
    ]
